### ISSUE TITLE
[Documentation Feedback]: Filter by timestamps code is broken

### ISSUE THREAD

**Issue by bobvanluijt** [weaviate/weaviate-io#290]
### Page URL

https://weaviate.io/developers/weaviate/current/graphql-references/filters.html#filter-by-timestamps

### User feedback

While answering [this](https://stackoverflow.com/questions/74599563/where-filter-with-multiple-operators-in-weaviate/74600216) question I noticed that there is an error in the docs.

1. `Greater` is not a valid operator
2. `valueDate` in the example results in an error

**Comment by dandv** [comment]
There are a few more issues beyond those two:

1. The example uses the `Equal` operator, instead of `GreaterThan`.
2. The error message generated by the example has a typo,
  > timestamps must be indexed to be filterable! add `indexTimestaps: true` to the invertedIndexConfig
  ([PR](https://github.com/semi-technologies/weaviate/pull/2396) sent)
3. The timestamps in `valueDate` are inconsistent among programming languages, e.g. `"2022-03-18T20:29:19.063-0500"` for GraphQL vs. `"2022-03-18T20:26:34.586-0500"` for the others. Java misses the milliseconds, and Go uses `lessThan` now.

Once the schema is altered to set `indexTimestamps: true`, I can test the example and fix the inconsistencies.

**Comment by databyjp** [comment]
I think this has been addressed; closing.
